set dotenv-load
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

[private]
[default]
default:
    @just --list --unsorted

install:
    deno install --frozen
    deno task postinstall

fix:
    deno fmt
    deno run -A npm:eslint . --fix

fmt:
    deno fmt

fmt-check:
    deno fmt --check

lint:
    deno lint
    deno run -A npm:eslint .

test:
    @echo "Frontend tests are not added yet"

check:
    deno fmt --check
    deno lint
    deno run -A npm:eslint .

build:
    deno task build

run:
    deno task dev

all: fix fmt lint test
