"""align game session schema with runtime initialization contract

Revision ID: 230227e69a40
Revises: c37da42cf767
Create Date: 2026-05-06 04:04:08.442734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230227e69a40'
down_revision: Union[str, Sequence[str], None] = 'c37da42cf767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'room_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=8),
               nullable=True,
               schema='management')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'room_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               schema='management')
    # ### end Alembic commands ###
