"""init management schema

Revision ID: c37da42cf767
Revises: 
Create Date: 2026-04-16 19:32:14.093922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c37da42cf767'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('room_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['management.quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_table('questions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selection_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['management.quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_index(op.f('ix_management_questions_quiz_id'), 'questions', ['quiz_id'], unique=False, schema='management')
    op.create_table('question_options',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['management.questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_table('session_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('player_nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['management.game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_participants', schema='management')
    op.drop_table('question_options', schema='management')
    op.drop_index(op.f('ix_management_questions_quiz_id'), table_name='questions', schema='management')
    op.drop_table('questions', schema='management')
    op.drop_table('game_sessions', schema='management')
    op.drop_table('quizzes', schema='management')
    # ### end Alembic commands ###
