set dotenv-load
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# List recipes
[private]
[default]
default:
    @just --list --unsorted

# Install service dependencies
install:
    uv sync

# Format and fix Python code
fmt:
    uv run ruff format .
    uv run ruff check . --fix

# Run Python tests
test:
    uv run pytest tests

# Check Python code and run tests
check:
    uv run ruff format . --check
    uv run ruff check .
    @just test

# Export OpenAPI spec
openapi:
    uv run python -m quiz_management.openapi.export
