set dotenv-load := true
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

[private]
[default]
default:
    @just --list --unsorted

install:
    bun install

fix:
    bun run lint:fix

fmt:
    bun run format

fmt-check:
    bun run format:check

lint:
    bun run lint

test:
    @echo "Frontend tests are not added yet"

check: fmt-check lint test

all: fix fmt lint test
