package session

import "errors"

var (
	ErrNotImplemented          = errors.New("not implemented")
	ErrInvalidParams           = errors.New("invalid params")
	ErrSessionNotFound         = errors.New("session not found in management")
	ErrSessionRuntimeNotFound  = errors.New("session runtime not found")
	ErrSessionRuntimeConflict  = errors.New("session runtime conflict")
	ErrSessionAlreadyFinished  = errors.New("session already finished")
	ErrBootstrapFetchFailed    = errors.New("failed to fetch bootstrap data")
	ErrRoomCodeUnavailable     = errors.New("could not generate unique room code")
	ErrRuntimeStoreUnavailable = errors.New("runtime storage unavailable")
	ErrUnauthorized            = errors.New("unauthorized")
	ErrForbidden               = errors.New("forbidden")
	ErrRoomNotFound            = errors.New("room not found")
	ErrNicknameTaken           = errors.New("nickname already taken")
	ErrParticipantNotFound     = errors.New("participant not found")
	ErrInvalidParticipantToken = errors.New("invalid participant token")
	ErrInvalidStateTransition  = errors.New("invalid state transition")
	ErrGameAlreadyStarted      = errors.New("game already started")
	ErrGameAlreadyFinished     = errors.New("game already finished")
	ErrQuestionNotActive       = errors.New("question not active")
	ErrAnswerAlreadySubmitted  = errors.New("answer already submitted")
	ErrInvalidAnswerPayload    = errors.New("invalid answer payload")
	ErrOptionNotFound          = errors.New("option not found")
	ErrOptionNotInQuestion     = errors.New("option not in question")
	ErrSelectionCountInvalid   = errors.New("selection count invalid")
	ErrInternal                = errors.New("internal error")
)
